Repository VulpesLegan/MITHRAStation, pull requests merged in 2018-10, with the labels that each got.

#9 Gigantic QoL Patch
  code/_onclick/click.dm
  code/game/machinery/alarm.dm
  code/game/machinery/kitchen/microwave.dm
  code/game/machinery/pipe/construction.dm
  code/game/machinery/washing_machine.dm
  code/game/objects/items/devices/flashlight.dm
  code/modules/clothing/masks/breath.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/emote_vr.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/species/station/monkey.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/mob/living/carbon/human/species/station/station_vr.dm
  code/modules/power/apc.dm
  mithrastation.dme
  sound/goonstation/LICENSE.md
  sound/goonstation/effects/crystalshatter.ogg
  sound/goonstation/effects/gib.ogg
  sound/goonstation/effects/robogib.ogg
  sound/goonstation/effects/screech.ogg
  sound/goonstation/effects/superfart.ogg
  sound/goonstation/machines/ambicomp1.ogg
  sound/goonstation/machines/ambicomp2.ogg
  sound/goonstation/machines/ambicomp3.ogg
  sound/goonstation/machines/printer_dotmatrix.ogg
  sound/goonstation/machines/printer_thermal.ogg
  sound/goonstation/misc/NewRound1.ogg
  sound/goonstation/misc/NewRound2.ogg
  sound/goonstation/misc/Scissor.ogg
  sound/goonstation/misc/airraid_loop.ogg
  sound/goonstation/misc/bell.ogg
  sound/goonstation/misc/burp_alien.ogg
  sound/goonstation/misc/drinkfizz.ogg
  sound/goonstation/misc/fuse.ogg
  sound/goonstation/misc/gurggle.ogg
  sound/goonstation/misc/klaxon.ogg
  sound/goonstation/misc/matchstick_light.ogg
  sound/goonstation/voice/female_scream.ogg
  sound/goonstation/voice/growl1.ogg
  sound/goonstation/voice/growl2.ogg
  sound/goonstation/voice/growl3.ogg
  sound/goonstation/voice/howl.ogg
  sound/goonstation/voice/male_scream.ogg
  sound/goonstation/voice/monkey_scream.ogg
  sound/goonstation/voice/robot_scream.ogg
Labels: Ready To Merge

#11 Small Southern-Cross Edits #3
  code/modules/lore_codex/codex.dm
  code/modules/lore_codex/legal_code_data/main.dm
  code/modules/lore_codex/lore_data/important_locations.dm
  maps/southern_cross/southern_cross-1.dmm
  maps/southern_cross/southern_cross-2.dmm
  maps/southern_cross/southern_cross-3.dmm
  maps/southern_cross/southern_cross-4.dmm
  maps/southern_cross/southern_cross-5.dmm
  maps/southern_cross/southern_cross-6.dmm
  maps/southern_cross/southern_cross-7.dmm
  mithrastation.dme
Labels: Map Change / Issue, Ready To Merge, Southern Cross

#14 Small Southern-Cross Edits #4
  code/game/machinery/cryopod_vr.dm
  code/modules/paperwork/paper.dm
  maps/southern_cross/southern_cross-1.dmm
  maps/southern_cross/southern_cross-3.dmm
  maps/southern_cross/southern_cross-6.dmm
  maps/southern_cross/southern_cross-7.dmm
Labels: Map Change / Issue, Ready To Merge, Southern Cross

#15 Slight Cleanup And Events Changes
  code/global.dm
  code/modules/events/atmos_leak.dm
  code/modules/events/brand_intelligence.dm
  code/modules/events/event_container.dm
  code/modules/events/event_container_vr.dm
  code/modules/events/ion_storm.dm
  code/modules/events/radiation_storm.dm
  code/modules/vore/fluffstuff/custom_boxes_vr.dm
  code/modules/vore/fluffstuff/custom_clothes_vr.dm
  code/modules/vore/fluffstuff/custom_guns_vr.dm
  code/modules/vore/fluffstuff/custom_items_vr.dm
  code/modules/vore/fluffstuff/custom_mecha_vr.dm
  code/modules/vore/fluffstuff/custom_permits_vr.dm
  mithrastation.dme
Labels: Informational, Ready To Merge

#16 Fixes Various Oversights
  maps/southern_cross/southern_cross-1.dmm
Labels: Map Change / Issue, Ready To Merge, Southern Cross

#17 Solves Centcomm Map Madness
  icons/misc/title_mr.png
  maps/southern_cross/southern_cross-6.dmm
Labels: Map Change / Issue, Ready To Merge, Southern Cross

#21 Whitelist Cleanup + Zigfie's Cyberlimbs
  code/datums/supplypacks/robotics.dm
  code/datums/supplypacks/robotics_vr.dm
  code/modules/organs/robolimbs_vr.dm
  config/alienwhitelist.txt
  config/custom_items.txt
  config/custom_sprites.txt
  config/jobwhitelist.txt
  icons/mob/human_races/cyberlimbs/_fluff_/aronai.dmi.disabled
  icons/mob/human_races/cyberlimbs/_fluff_/cook_custom.dmi
  icons/mob/human_races/cyberlimbs/_fluff_/rahboop.dmi.disabled
  icons/mob/human_races/cyberlimbs/_fluff_/serdykov.dmi.disabled
Labels: Fluff, Ready To Merge

#22 Branch Sync [Branch]
  code/datums/supplypacks/robotics.dm
  code/datums/supplypacks/robotics_vr.dm
  code/modules/organs/robolimbs_vr.dm
  config/alienwhitelist.txt
  config/custom_items.txt
  config/custom_sprites.txt
  config/jobwhitelist.txt
  icons/mob/human_races/cyberlimbs/_fluff_/aronai.dmi.disabled
  icons/mob/human_races/cyberlimbs/_fluff_/cook_custom.dmi
  icons/mob/human_races/cyberlimbs/_fluff_/rahboop.dmi.disabled
  icons/mob/human_races/cyberlimbs/_fluff_/serdykov.dmi.disabled
Labels: Ready To Merge, Work In Progress

#18 Race Overhaul Part 1
  code/game/objects/effects/spiders.dm
  code/modules/mob/living/carbon/human/species/station/seromi.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/mob/living/carbon/human/species/station/station_special_vr.dm
  code/modules/mob/living/carbon/human/species/station/station_vr.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  code/modules/vore/appearance/spider_taur_powers_vr.dm
Labels: Fluff, Ready To Merge

#31 Adds the Mithra Modular Folder, Toriwrench, tennis balls and a bunch of loadout things
  mithrastation.dme
  modular_mithra/README.md
  modular_mithra/code/game/objects/balls.dm
  modular_mithra/code/game/objects/items/weapons/tools.dm
  modular_mithra/code/modules/clothing/glasses/glasses.dm
  modular_mithra/icons/mob/inhands/balls_left.dmi
  modular_mithra/icons/mob/inhands/balls_right.dmi
  modular_mithra/icons/mob/mouthball.dmi
  modular_mithra/icons/obj/balls.dmi
  modular_mithra/icons/obj/tools.dmi
  modular_mithra/loadout/loadout_eyes.dm
  modular_mithra/loadout/loadout_general.dm
  modular_mithra/loadout/loadout_head.dm
  modular_mithra/loadout/loadout_suit.dm
Labels: Fluff, Ready To Merge

#32 Re-adds the EAL
  code/modules/client/preference_setup/loadout/loadout_utility.dm
Labels: Fluff, Ready To Merge

#34 Gives pilots EVA and External Airlock access
  maps/southern_cross/southern_cross_jobs.dm
Labels: Map Change / Issue, Ready To Merge

#35 Event Changes And Cleanup
  code/modules/events/event_container.dm
  code/modules/paperwork/paper.dm
  mithrastation.dme
  modular_mithra/code/modules/paperwork/paper.dm
Labels: Informational, Ready To Merge

#37 Ports the X-01 Multiphase Energy Gun from TG
  mithrastation.dme
  modular_mithra/multiphase/gun.dm
  modular_mithra/multiphase/left.dmi
  modular_mithra/multiphase/locker.dm
  modular_mithra/multiphase/multiphase.dmi
  modular_mithra/multiphase/projectile.dm
  modular_mithra/multiphase/right.dmi
Labels: Addition, Fluff, Sprites

#38 Fixes Custom Species being "Custom Species" instead of the Custom Species
  code/modules/mob/living/carbon/human/descriptors/_descriptors.dm
Labels: Bug, Fluff, Ready To Merge

#39 Fixes Time (Thanks KTT)
  code/_helpers/time.dm
  code/global.dm
  code/modules/mob/living/carbon/human/species/station/protean_vr/protean_species.dm
Labels: Fluff, Ready To Merge

#43 Small Southern-Cross Edits #6
  code/global.dm
  code/hub.dm
  maps/southern_cross/southern_cross-1.dmm
  mithrastation.dme
  nano/css/layout_default.css
  nano/images/nanomapBackground.png
  nano/images/nanomap_z1.png
  nano/images/nanomap_z10.png
  nano/images/nanomap_z2.png
  nano/images/nanomap_z3.png
  nano/images/nanomap_z5.png
  nano/images/nanomap_z6.png
  nano/images/nanomap_z7.png
  nano/images/nanomap_z8.png
  nano/images/nanomap_z9.png
Labels: Map Change / Issue, Ready To Merge, Southern Cross

#44 Important Commit
  icons/mithraicon.png
  interface/skin.dmf
  maps/~map_system/maps.dm
Labels: Map Change / Issue, Priority: HIGH, Ready To Merge, Southern Cross

#45 Small Fix
  interface/skin.dmf
Labels: Bug, Priority: HIGH

#46 ITS LATE, OK?
  interface/skin.dmf
Labels: Bug, Priority: HIGH

#40 Pilot helmets cover the eyes
  modular_mithra/code/modules/clothing/head/pilot_helmet.dm
Labels: Fluff, Ready To Merge

#47 Computer Sprite Edit and Teshari Slowdown Removal
  code/modules/mob/living/carbon/human/species/station/seromi.dm
  icons/obj/computer_vr.dmi
Labels: Ready To Merge, Sprites, Tweak

#48 Makes the X-01 Multiphase Energy Gun holsterable
  mithrastation.dme
  modular_mithra/code/modules/projectiles/guns/energy/laser.dm
  modular_mithra/multiphase/gun.dm
Labels: Tweak
