Repository VulpesLegan/MITHRAStation, pull requests merged in 2018-11, with the labels that each got.

#52 Removes vore dreams
  code/modules/flufftext/Dreaming.dm
Labels: Fluff, Ready To Merge

#56 Adds Hacked Jukebox Song
  sound/music/e1m1.ogg
Labels: Fluff, Ready To Merge

#55 Small Southern-Cross Edits #7
  code/controllers/autotransfer.dm
  code/game/area/Space Station 13 areas.dm
  code/modules/maps/tg/map_template.dm
  code/modules/maps/tg/map_template_vr.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/shuttles/shuttles_web.dm
  icons/obj/radio_vr.dmi
  maps/southern_cross/backup/southern_cross-1.dmm
  maps/southern_cross/backup/southern_cross-3.dmm
  maps/southern_cross/backup/southern_cross-4.dmm
  maps/southern_cross/backup/southern_cross-5.dmm
  maps/southern_cross/backup/southern_cross-6.dmm
  maps/southern_cross/backup/southern_cross-8.dmm
  maps/southern_cross/items/encryptionkey_vr.dm
  maps/southern_cross/items/headset_sc.dm
  maps/southern_cross/items/headset_vr.dm
  maps/southern_cross/job/outfits_vr.dm
  maps/southern_cross/southern_cross-1.dmm
  maps/southern_cross/southern_cross-2.dmm
  maps/southern_cross/southern_cross-3.dmm
  maps/southern_cross/southern_cross-4.dmm
  maps/southern_cross/southern_cross-5.dmm
  maps/southern_cross/southern_cross-6.dmm
  maps/southern_cross/southern_cross-7.dmm
  maps/southern_cross/southern_cross-8.dmm
  maps/southern_cross/southern_cross-9.dmm
  maps/southern_cross/southern_cross_jobs.dm
  maps/southern_cross/southern_cross_jobs_vr.dm
  maps/southern_cross/structures/closets/misc_vr.dm
Labels: Map Change / Issue, Point Of Interest, QoL, Ready To Merge, Southern Cross, Sprites

#57 Small Fix
  maps/southern_cross/southern_cross-1.dmm
Labels: Map Change / Issue, Ready To Merge, Southern Cross

#59 Small Southern-Cross Edits #8
  icons/obj/Cryogenic2_vr.dmi
  maps/southern_cross/southern_cross-1.dmm
  maps/southern_cross/southern_cross-3.dmm
Labels: Map Change / Issue, Point Of Interest, QoL, Ready To Merge, Southern Cross, Sprites

#60 Final Patch
  maps/southern_cross/southern_cross-1.dmm
Labels: Bug, Priority: HIGH

#53 Fuck KHI, Part 1 - The start of the comprehensive review and purging of any and all references to the corporation tentatively known as KHI, to bring the codebase in-line with MITHRA Lore
  code/modules/busy_space_vr/organizations.dm
  code/modules/resleeving/implant.dm
  mithrastation.dme
  modular_mithra/lore_override/glasses.dm
  modular_mithra/lore_override/guns.dm
  modular_mithra/lore_override/sleevecard.dm
Labels: Fluff, Ready To Merge, Removal

#61 Removes and restricts size changing
  code/game/machinery/vending_vr.dm
  code/game/objects/structures/trash_pile.dm
  code/modules/client/preference_setup/vore/02_size.dm
  code/modules/nifsoft/software/15_misc.dm
  code/modules/reagents/Chemistry-Recipes_vr.dm
  code/modules/research/designs_vr.dm
  code/modules/resleeving/designer.dm
  code/modules/virus2/effect_vr.dm
  code/modules/vore/eating/vorepanel_vr.dm
  code/modules/vore/resizing/resize_vr.dm
Labels: Fluff, Priority: HIGH, Ready To Merge, Removal, Tweak

#63 Make Flatland Zorrens properly greyscaled
  mithrastation.dme
  modular_mithra/flatlandzorrenfix/override.dm
  modular_mithra/flatlandzorrenfix/r_fennec_vr.dmi
Labels: Fix, Ready To Merge, Sprites

#62 Extra proximity sensor in the Robuttics closet for Robutticists in Robuttics making Robutts
  maps/southern_cross/southern_cross-1.dmm
Labels: Map Change / Issue, Ready To Merge, Southern Cross

#67 Radios now get a panic function.
  code/controllers/communications.dm
  code/game/objects/items/devices/radio/radio.dm
  code/stylesheet.dm
  maps/southern_cross/southern_cross_presets.dm
  mithrastation.dme
  modular_mithra/radio_panic_button/README.MD
  modular_mithra/radio_panic_button/encryption_keys.dm
  modular_mithra/radio_panic_button/radio.dm
  nano/templates/radio_basic.tmpl
Labels: Addition, QoL

#68 Event and Antag Selection Tweaks
  code/modules/client/preference_setup/antagonism/02_candidacy.dm
  code/modules/events/event_container.dm
Labels: Balancing, Fix, Tweak

#69 Beta radios
  modular_mithra/motorola_radio/radiola.dm
  modular_mithra/motorola_radio/xpr.dmi
Labels: Sprites

#70 Shield generator/meteor storm tweaks
  code/game/gamemodes/meteor/meteors.dm
  code/modules/shieldgen/energy_field.dm
  mithrastation.dme
  modular_mithra/motorola_radio/radiola.dm
  modular_mithra/shield_generator/shields_and_generator_overrides.dm
Labels: Balancing, Tweak

#73 Tweak event weights again.
  code/modules/events/event_container.dm
Labels: Balancing, Priority: HIGH, QoL, Tweak

#72 Adds admin feedback and logging for panic alarms
  modular_mithra/radio_panic_button/radio.dm
Labels: Administrative, Logging and Feedback
